---
- name: Delete user annd group
  hosts: 44.203.74.41
  tasks:
  - name: Delete user
    user:
      name: anyone
      state: absent
      remove: yes 
  - name:  Delete group
    group:
      name: team
      state: absent
