---
- name: User management
  hosts: ip
  tasks:
  - name: Add User
    user:
      name: anonymous
      comment: test user
      uid: 107
      group: team
      shell: /bin/bash
  - name: Add a group
    group:
      name: anonymous
      state: present
